<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="WebApplication1.Home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h1><b>Welcome to Hogwarts: School Of Witchcraft and Wizardry</b></h1>
    <h2><i>The finest school of witchcraft and wizardry in the world.</i></h2>
    <br />
    <h3>Hogwarts School of Witchcraft and Wizardry, often shortened to Hogwarts, was a Scottish wizarding school located in the Scottish Highlands. It accepted any magical student residing in the islands of Great Britain and Ireland at the age of eleven years old at the start of the incoming term for enrolment It was a state-owned school, funded by the British Ministry of Magic.</h3>
    <h3>The precise location of the school could never be uncovered because it was rendered Unplottable. To Muggles, non wizards, the school appeared to be an old, abandoned castle. Similarly, most wizarding schools' locations were protected in order to protect the students and schools themselves from any harm.Established around the 10th century, Hogwarts was considered to be one of the finest magical institutions in the wizarding world, though other notable schools included Beauxbatons Academy of Magic in France, the Durmstrang Institute implied to be in northern Europe, and Ilvermorny School of Witchcraft and Wizardry in the United States.</h3>
    <h3>British and Irish children with magical abilities were enrolled at birth by the Quill of Acceptance and Book of Admittance, and acceptance was confirmed by owl post at age eleven. However, if the child in question was a Muggle-born or a half-blood with no knowledge of the wizarding world, a special messenger from the school visited the child and his or her family in order to inform them of their magical heritage and the existence of the wizarding world.It was possible for students to transfer to the school as well.The school's motto was Draco Dormiens Nunquam Titillandus, which, translated from Latin, means "Never tickle a sleeping dragon"</h3>
    <br />
    <h1><b>The History of Hogwarts</b></h1>
    <br />
    <h3>Hogwarts was founded around 990 A.D. by four of the greatest wizards and witches of the age: <b>Godric Gryffindor, Helga Hufflepuff, Rowena Ravenclaw, and Salazar Slytherin</b>. They each represented an aspect of personality that they wanted to bring out in new students. They also placed certain protective enchantments in place to ensure the well-being of their students, for which reason the castle and grounds had both always been protected with Anti-Apparition Charms. Around the same time, the four founders employed the school's first caretaker, Hankerton Humble, who would often clash with Peeves, the resident poltergeist, which he would have in common with every successive caretaker after him in the history of Hogwarts.</h3>
    <h3>Although the four founders cooperated well for a time, shortly after founding the school, Slytherin had a falling out with the other founders about blood purity, and wanted to admit only pure-blood students. He felt only pure-blooded students deserved to learn magic, and those of other ancestry such as Muggle-borns and half-bloods were unworthy. The other three founders all disagreed, especially Gryffindor. Slytherin left the school, but not before secretly building the Chamber of Secrets. He foretold that only his own heir would be able to open it once they arrived at the school, and the heir would unleash a murderous basilisk living inside to purge the school of all Muggle-born students. Despite the fact that the founders of Hogwarts were effectively in charge of the school during their time, none of them held the title of Headmaster or Headmistress of the school, as that was only used sometime after Slytherin's departure, and held by another wizard, who was the first person to be entrusted the stewardship of Hogwarts Castle and the surrounding grounds after the three remaining founders passed away.The first student class to graduate from the school were immortalised in a portrait that would continue to hang in the school for over 1000 years</h3>
    <br />
</asp:Content>
